
export const SUBSCRIBERS_FETCH_SUCCESS = 'SUBSCRIBERS_FETCH_SUCCESS';
export const FOLLOWERS_FETCH_SUCCESS = 'FOLLOWERS_FETCH_SUCCESS';

export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
